version: "3"
services:
  app:
    image: registry.cn-shanghai.aliyuncs.com/nocobase/nocobase:1.8.25
    #image: nocobase/nocobase:latest
    environment:
      - APP_PUBLIC_PATH=/nb/

      - APP_KEY=your-secret-key # Replace it with your own app key
      - DB_DIALECT=postgres
      - DB_HOST=nbdb
      - DB_DATABASE=nocobase
      - DB_USER=nocobase
      - DB_PASSWORD=nocobase
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - "13000:80"
    depends_on:
      - nbdb
    init: true

  nbdb:
    image: postgres:10
    restart: always
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_USER: nocobase
      POSTGRES_DB: nocobase
      POSTGRES_PASSWORD: nocobase
    volumes:
      - ./storage/db/postgres:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.13.2
    ports:
      - "8880:8080"
    depends_on:
      - nbdb
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://nocobase:nocobase@nbdb:5432/hasura
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://nocobase:nocobase@nbdb:5432/nocobase
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: hasuraPassw0rd
      
  n8n:
    image: n8nio/n8n:1.71.3
    restart: always
    ports:
      - "5678:5678"
    environment:
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=24
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=2000

      - N8N_SECURE_COOKIE=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=nbdb
      - DB_POSTGRESDB_PORT=5432
      
      - DB_POSTGRESDB_DATABASE=n8n
      
      - DB_POSTGRESDB_USER=nocobase
      - DB_POSTGRESDB_PASSWORD=nocobase
      - GENERIC_TIMEZONE=Asia/Shanghai
      - TZ=Asia/Shanghai
    links:
      - nbdb
    depends_on:
      - nbdb      
    volumes:
      - ./n8n:/home/node/.n8n
