version: "3"
networks:
  default:
    external:
      name: axelor_default

services:
  app01:
    image: shawoo/openresty
    restart: always
    working_dir: /usr/local/openresty/
    ports:
      - "3501:3500"

  app01-dapr:
    image: "shawoo/dapr:1.8.4"
    command: ["./daprd",
     "-app-id", "app01",
     "-app-port", "80",
     "-placement-host-address", "placement:50005",
     "-components-path", "/dapr/components",
     "-config", "/dapr/config.yaml"]
    #volumes:
    #   - "./dapr/:/dapr/"
    depends_on:
      - app01
    network_mode: "service:app01"
